// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TODOLISTAPI.Models;

#nullable disable

namespace TODOLISTAPI.Migrations
{
    [DbContext(typeof(TodoSmartAlertsContext))]
    partial class TodoSmartAlertsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TODOLISTAPI.Models.ForwardedTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ForwardedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ForwardedBy")
                        .HasColumnType("int");

                    b.Property<int>("ForwardedTo")
                        .HasColumnType("int");

                    b.Property<int>("OriginalTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Forwarde__3214EC075A61EDB1");

                    b.HasIndex("ForwardedBy");

                    b.HasIndex("ForwardedTo");

                    b.HasIndex("OriginalTaskId");

                    b.ToTable("ForwardedTasks");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Member");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__GroupMem__3214EC0784E9E556");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.GroupsUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__GroupsUs__3214EC0767F16719");

                    b.HasIndex("CreatedBy");

                    b.ToTable("GroupsUser", (string)null);
                });

            modelBuilder.Entity("TODOLISTAPI.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC07EB8250D3");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.SnoozeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("SnoozedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WakeAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__SnoozeLo__3214EC07D8C584B4");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("SnoozeLogs");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("DueTime")
                        .HasColumnType("time");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsTimeBased")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Tasks__3214EC07FA8CA435");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GroupId");

                    b.ToTable("Tasks", t =>
                        {
                            t.HasTrigger("trg_Tasks_UpdatedAt");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TODOLISTAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC070A53C32D");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534AF9C5684")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.UserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DarkModeEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("NotificationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SnoozeMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UserSett__3214EC070E164229");

                    b.HasIndex(new[] { "UserId" }, "UQ__UserSett__1788CC4D7B6F48F8")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.ForwardedTask", b =>
                {
                    b.HasOne("TODOLISTAPI.Models.User", "ForwardedByNavigation")
                        .WithMany("ForwardedTaskForwardedByNavigations")
                        .HasForeignKey("ForwardedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Forwarded_By");

                    b.HasOne("TODOLISTAPI.Models.User", "ForwardedToNavigation")
                        .WithMany("ForwardedTaskForwardedToNavigations")
                        .HasForeignKey("ForwardedTo")
                        .IsRequired()
                        .HasConstraintName("FK_Forwarded_To");

                    b.HasOne("TODOLISTAPI.Models.Task", "OriginalTask")
                        .WithMany("ForwardedTasks")
                        .HasForeignKey("OriginalTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Forwarded_Task");

                    b.Navigation("ForwardedByNavigation");

                    b.Navigation("ForwardedToNavigation");

                    b.Navigation("OriginalTask");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.GroupMember", b =>
                {
                    b.HasOne("TODOLISTAPI.Models.GroupsUser", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GroupMembers_Group");

                    b.HasOne("TODOLISTAPI.Models.User", "User")
                        .WithMany("GroupMembers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_GroupMembers_User");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.GroupsUser", b =>
                {
                    b.HasOne("TODOLISTAPI.Models.User", "CreatedByNavigation")
                        .WithMany("GroupsUsers")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_GroupsUser_CreatedBy");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.Notification", b =>
                {
                    b.HasOne("TODOLISTAPI.Models.Task", "Task")
                        .WithMany("Notifications")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Task");

                    b.HasOne("TODOLISTAPI.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_User");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.SnoozeLog", b =>
                {
                    b.HasOne("TODOLISTAPI.Models.Task", "Task")
                        .WithMany("SnoozeLogs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Snooze_Task");

                    b.HasOne("TODOLISTAPI.Models.User", "User")
                        .WithMany("SnoozeLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Snooze_User");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.Task", b =>
                {
                    b.HasOne("TODOLISTAPI.Models.User", "AssignedToNavigation")
                        .WithMany("TaskAssignedToNavigations")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("FK_Tasks_AssignedTo");

                    b.HasOne("TODOLISTAPI.Models.User", "CreatedByNavigation")
                        .WithMany("TaskCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Tasks_CreatedBy");

                    b.HasOne("TODOLISTAPI.Models.GroupsUser", "Group")
                        .WithMany("Tasks")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Tasks_Group");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.UserSetting", b =>
                {
                    b.HasOne("TODOLISTAPI.Models.User", "User")
                        .WithOne("UserSetting")
                        .HasForeignKey("TODOLISTAPI.Models.UserSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSettings_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.GroupsUser", b =>
                {
                    b.Navigation("GroupMembers");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.Task", b =>
                {
                    b.Navigation("ForwardedTasks");

                    b.Navigation("Notifications");

                    b.Navigation("SnoozeLogs");
                });

            modelBuilder.Entity("TODOLISTAPI.Models.User", b =>
                {
                    b.Navigation("ForwardedTaskForwardedByNavigations");

                    b.Navigation("ForwardedTaskForwardedToNavigations");

                    b.Navigation("GroupMembers");

                    b.Navigation("GroupsUsers");

                    b.Navigation("Notifications");

                    b.Navigation("SnoozeLogs");

                    b.Navigation("TaskAssignedToNavigations");

                    b.Navigation("TaskCreatedByNavigations");

                    b.Navigation("UserSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
